<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_button_Admin</name>
   <tag></tag>
   <elementGuidId>d6796cc3-22cb-45c7-b844-e2d9bdf2345e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-default.disabled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08d98b31-68d9-4e52-9a8c-6d5bdd7631bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default disabled</value>
      <webElementGuid>faca50bc-96ef-4d06-9a21-2ffcc63aaa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>9861ec1d-67f7-47c3-8d63-81eb0c8b279c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_843653601&quot;)/td[@class=&quot;text-left&quot;]/button[@class=&quot;btn btn-default disabled&quot;]</value>
      <webElementGuid>ba6c0121-b0c2-47aa-802a-a3634287874a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_843653601']/td[3]/button</value>
      <webElementGuid>4cebb6fe-7c7a-467c-bc15-b5f4544a15ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='organization7441'])[1]/following::button[1]</value>
      <webElementGuid>cc55feea-f516-461a-8efc-53f1647d6130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permission'])[1]/following::button[1]</value>
      <webElementGuid>8ea2ea11-8628-4f41-b7c8-7bb677cd7a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::button[1]</value>
      <webElementGuid>c975b3dd-9224-4f47-ac75-5b97056b4270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Device'])[1]/preceding::button[1]</value>
      <webElementGuid>76ee42b9-0d39-45c3-8023-d2484d83cb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin']/parent::*</value>
      <webElementGuid>29cfa83c-5326-4a4f-a4ff-ea46eb7a898d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/button</value>
      <webElementGuid>13e2bbcb-5fe0-4af6-80bb-3f8e83f488da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Admin' or . = 'Admin')]</value>
      <webElementGuid>8728c43c-622a-43ce-8a5a-1254dfacdf22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
