<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Create Organization</name>
   <tag></tag>
   <elementGuidId>2ce6ff22-bf41-4a6b-87f2-5245b6cdb966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;string_create&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='string_create']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>a7e3c8c3-64f1-4e01-b0a0-983e1607e535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>string_create</value>
      <webElementGuid>49fc3311-d1e1-468e-aecc-36c6c85ecd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Organization</value>
      <webElementGuid>ed2cb6c5-ecc5-4b30-9780-6c4731e9e454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organizations_create&quot;)/lang[1]</value>
      <webElementGuid>c1453029-2a0d-4a35-9dc0-6ef19e331091</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='string_create']</value>
      <webElementGuid>3709b4b0-5dcc-4803-8efa-156ab4379cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='organizations_create']/lang</value>
      <webElementGuid>a3f2fa3f-70e5-44e4-b0f7-63585392f5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::lang[1]</value>
      <webElementGuid>eda35b46-cca5-478c-963e-83a684a18aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::lang[2]</value>
      <webElementGuid>2c367b63-1b16-4476-91a6-1c0dfe1c0416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Report'])[1]/preceding::lang[1]</value>
      <webElementGuid>588f5e73-c7f0-4fa5-9dba-08956982cc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::lang[2]</value>
      <webElementGuid>36a3102c-9845-4d1c-af35-d1d2cf2f176c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Organization']/parent::*</value>
      <webElementGuid>68039c3a-6fb7-4b17-bfd3-28ea43aba9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/div/ul/li/a/lang</value>
      <webElementGuid>323916fe-883b-4c37-bca7-0d99fad29013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'string_create' and (text() = 'Create Organization' or . = 'Create Organization')]</value>
      <webElementGuid>6708c07e-7339-4d1c-8217-5a521f6b44ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
