<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Organizations</name>
   <tag></tag>
   <elementGuidId>9b250c01-a6ca-4b48-9aa8-53e5794caa5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;label_organizations&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[7]/td/a/lang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>c98a54f9-7d2f-49fa-9a4f-d199f71f327c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-hidden-on-small text-center</value>
      <webElementGuid>135c1155-95df-4d11-b59b-9b7aefbb55c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label_organizations</value>
      <webElementGuid>7c891509-93bf-4c44-afa5-25e95fbdd554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-plural</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>77e1c205-c1b5-405e-b3a6-7435dc7e3ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Organizations</value>
      <webElementGuid>8c1ba867-ec8e-44b1-b881-470bf9dccf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_menu&quot;)/table[1]/tbody[1]/tr[7]/td[@class=&quot;text-center&quot;]/a[@class=&quot;active&quot;]/lang[@class=&quot;pica-hidden-on-small text-center&quot;]</value>
      <webElementGuid>ce309162-59e5-450a-8766-bfc066a3d327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='label_organizations']</value>
      <webElementGuid>b97a5531-baaf-49eb-8226-350d8c07db04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_menu']/table/tbody/tr[7]/td/a/lang</value>
      <webElementGuid>eee372f2-a21a-41a9-b54d-70e6b51b722d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[1]/following::lang[1]</value>
      <webElementGuid>250b7b8c-e5aa-4c5b-9513-4a5f8d9f27db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[1]/following::lang[2]</value>
      <webElementGuid>037e6072-ca05-40a9-bf51-1e42b233993a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Devices'])[1]/preceding::lang[1]</value>
      <webElementGuid>7d659f5d-3c24-48b6-9d2d-c9afbbaad760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurations'])[1]/preceding::lang[2]</value>
      <webElementGuid>35ba3ba2-c247-411b-953d-b457722c0886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Organizations']/parent::*</value>
      <webElementGuid>d38c6bc6-9161-48c8-83d9-fb2e31f501e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/a/lang</value>
      <webElementGuid>3d9fdebb-8ef9-497b-8395-c32de6a633fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'label_organizations' and (text() = 'Organizations' or . = 'Organizations')]</value>
      <webElementGuid>0ba2c6a4-2298-4d72-b5a8-f141955b26e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
