<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Log out_caret</name>
   <tag></tag>
   <elementGuidId>2dbe4de5-e5f6-45b7-ae3e-4a4379a61a0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_action_normal > div.pica-inline.dropdown > a.dropdown-toggle > span.caret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_action_normal']/div[2]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ebb9880d-9161-4030-b030-744fd11cdd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
      <webElementGuid>c42cddf6-a791-486c-8a7a-3c020a996bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_action_normal&quot;)/div[@class=&quot;pica-inline dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;caret&quot;]</value>
      <webElementGuid>96414b2f-e469-49a1-8a8e-bb1d0d29cd8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_action_normal']/div[2]/a/span[2]</value>
      <webElementGuid>38729638-9c18-4281-8142-f6ea74d85ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span[2]</value>
      <webElementGuid>5cb37e3a-8283-4a5f-8e42-9d279590a8ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
