<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Paste_pica-glyph glyphicons glyphicons_b7fcf2</name>
   <tag></tag>
   <elementGuidId>bd0f0dbe-e556-44e8-85e8-f50227d94bee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica-files-create-dropdown']/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pica-glyph.glyphicons.glyphicons-folder-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>705a9d90-cd7c-4762-a1fa-5ef78e441bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph glyphicons glyphicons-folder-plus</value>
      <webElementGuid>15060cc4-e08e-42a4-9318-907927dfd636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica-files-create-dropdown&quot;)/ul[@class=&quot;pica-arrow-left dropdown-menu&quot;]/li[@class=&quot;files-ui-create-dir&quot;]/a[1]/span[@class=&quot;pica-glyph glyphicons glyphicons-folder-plus&quot;]</value>
      <webElementGuid>5c28fa66-a76d-48d2-b392-dc11c7b6f725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica-files-create-dropdown']/ul/li/a/span</value>
      <webElementGuid>8ac68852-baa2-4861-8bb6-4d24d94a5733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//thead[3]/tr/th/div/ul/li/a/span</value>
      <webElementGuid>4ea85b73-3992-4bc9-9a1d-cbca39fc61d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
