<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_admin_to_organization</name>
   <tag></tag>
   <elementGuidId>eb3ff4d8-7b10-4acc-8e9f-9ec6e2c4552b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_organization_accounts > div.pica-inputlist-taginput.pica-taginput.form-group.input-group > div.pica-taginput-div.form-control > input.pica-taginput-input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a8e70ae-3393-440d-853f-13d78f7e8f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>646e525f-d83d-46ac-ae44-1db8dd1ac08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-taginput-input form-control</value>
      <webElementGuid>eb795cb8-5990-40da-b9b8-7b0ee93cacc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_add_account_by_name</value>
      <webElementGuid>acb7b785-12cd-4741-99ee-3fcb8d9d2e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>should-validate</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>16833851-e190-41c9-a3c0-b10a2c08a86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add an account by name</value>
      <webElementGuid>9fbeca39-d5e7-46e0-b252-af658403417f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_organization_accounts&quot;)/div[@class=&quot;pica-inputlist-taginput pica-taginput form-group input-group&quot;]/div[@class=&quot;pica-taginput-div form-control&quot;]/input[@class=&quot;pica-taginput-input form-control&quot;]</value>
      <webElementGuid>f033e16b-ab7c-49d1-be9d-5f47de6ec14b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='email']</value>
      <webElementGuid>7a25bb24-5892-4d68-ae7e-efb6050fa03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_organization_accounts']/div/div/input</value>
      <webElementGuid>10dc6e9a-a13b-40de-8d18-ce5c74b14c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>b4c3572c-bb24-4aa3-adc1-10c75861215b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Add an account by name']</value>
      <webElementGuid>14a5b537-421f-4c48-8d8b-804cb002d643</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
