<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check</name>
   <tag></tag>
   <elementGuidId>a3429950-7f86-4ef8-8bd4-af2871a1f7ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > span.glyphicons.glyphicons-unchecked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>26afaf1f-d93a-4d5e-8460-79ce6fc00e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-unchecked</value>
      <webElementGuid>d35531f8-8cd1-4237-a84c-4d710d6ae34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_1609638658&quot;)/td[@class=&quot;hidden-xs&quot;]/div[@class=&quot;pica-inline dropdown pull-right open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[2]/a[1]/span[@class=&quot;glyphicons glyphicons-unchecked&quot;]</value>
      <webElementGuid>fb348db1-e2a6-4890-b2d9-dead7df6e6fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='item_1609638658']/td[3]/div/ul/li[2]/a/span</value>
      <webElementGuid>46540e1a-b7e8-40cb-9903-912a22eafe2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>0a34f3e9-48b3-47c8-8c2d-e7fbfd8d4236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
