<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>password_case</name>
   <tag></tag>
   <elementGuidId>009b8dff-00ff-4409-932d-a33e72ef8458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_account_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0e0d53c-d49e-44a8-84b4-128e2090693a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_account_password</value>
      <webElementGuid>cae9ebdc-5d14-47b9-8899-35aaf5853988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-password form-control</value>
      <webElementGuid>97cc4d2e-fc53-4ee8-9cf0-b1d947e58c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a15ed066-a3d8-468b-bd87-65b5ad089470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>99cace4a-32fe-4f1a-96a3-08d085011eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_password</value>
      <webElementGuid>a593d3a4-a5a5-40aa-a5d9-fdbfbb645fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>8402562a-bf7e-4e10-8950-4e155e666f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Password policy</value>
      <webElementGuid>d3b40705-77d2-46fe-ab01-10d74d93dead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>popover</value>
      <webElementGuid>5a7bd301-02a8-47a7-8616-06864fd62a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>65b89fce-73db-46b4-bec7-4a47d8e30fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>b65c7517-8b66-420c-af6f-42737673f2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trigger</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>df58a664-2f04-4169-a14e-2601c0bd6c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>035bf59b-078a-4643-a4bf-9422e8be840a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-content</name>
      <type>Main</type>
      <value>&lt;h5>&lt;lang name=&quot;password_policy_uppercase&quot; class=&quot;profile_password_policy_uppercase pica-space-right-small label label-danger&quot;>At least one upper case letter&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_lowercase&quot; class=&quot;profile_password_policy_lowercase pica-space-right-small label label-danger&quot;>At least one lower case letter&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_digit&quot; class=&quot;profile_password_policy_digit pica-space-right-small label label-danger&quot;>At least one number&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_special&quot; class=&quot;profile_password_policy_special pica-space-right-small label label-danger&quot;>At least one special character&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_count&quot; class=&quot;profile_password_policy_count pica-space-right-small label label-danger&quot;>At least 8 characters&lt;/lang>&lt;/h5></value>
      <webElementGuid>891fae4e-f62c-48a5-87d7-c46efba48c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Password policy</value>
      <webElementGuid>649c59ff-3738-49c4-91d9-df9621c49346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>popover998933</value>
      <webElementGuid>a5b8e6fb-944f-40df-8786-6b9d4b6ee5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_password&quot;)</value>
      <webElementGuid>1470451a-c3d6-40e5-9396-fd596df7f28e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_account_password']</value>
      <webElementGuid>7f2f17a9-2e6f-4d86-bb32-795b6bb9fc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_dialog']/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>9bf02c59-683e-42e1-b335-f1d14446d532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a3243f9f-4596-45f6-bda0-525b1c70abef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_account_password' and @type = 'text' and @placeholder = 'Password' and @title = 'Password policy']</value>
      <webElementGuid>af588899-f2fe-468e-8540-ae82ba162cb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
