<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter a new Name_pencil</name>
   <tag></tag>
   <elementGuidId>60486c0d-463e-40ca-8f73-9fe5a0256ae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_input_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pica_input_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac8cbbe2-e98e-4d04-8cc2-5c5e2cc56d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_input_text</value>
      <webElementGuid>ceb31863-8925-43ea-beb2-e6d64e088540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bb224510-46c5-4387-afda-d523d452f7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pencil</value>
      <webElementGuid>4ead56ae-114c-475b-9e71-99a86b6e9fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d64b205-14e9-4cbc-8aa4-7ca0062dbef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_input</value>
      <webElementGuid>a325ba01-1d59-49cc-8b0e-156eae25c41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert here</value>
      <webElementGuid>f58c4b5b-9426-4d47-a553-45d62cd35f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_input_text&quot;)</value>
      <webElementGuid>0d1d137e-8729-40dd-abe1-44d42701697a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_input_text']</value>
      <webElementGuid>65ee2fb6-783b-4c7e-89b3-2dcb5a954cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_input_dialog']/div/div/div[2]/div/input</value>
      <webElementGuid>18993ee3-c9e3-427b-8c63-c8ae66f72b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c5fb6428-09f5-4d93-b70b-fd87605d4dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_input_text' and @name = 'pencil' and @type = 'text' and @placeholder = 'Insert here']</value>
      <webElementGuid>ac3151e5-14ca-4796-859d-8de4b3a5048c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
