<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_input</name>
   <tag></tag>
   <elementGuidId>e06e7f6f-0f50-4b70-9ff0-881801252b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_action_search_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pica_action_search_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>909c033d-8d7c-4a39-8180-bc6cf8938756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_action_search_input</value>
      <webElementGuid>4217f41d-cd39-4c2b-a152-605569482dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14219812-27f9-4d74-a705-8737285423d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_search</value>
      <webElementGuid>24737291-a636-4cc6-83fc-41038afb3001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>search input</value>
      <webElementGuid>e5a07083-a311-46da-a2f6-c724ad149f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter search term</value>
      <webElementGuid>1cf7ab4e-353b-440e-91c6-d982c5bb990a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_action_search_input&quot;)</value>
      <webElementGuid>ddd7757a-8526-4a6e-8895-bffc9fe61df9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_action_search_input']</value>
      <webElementGuid>d518e82a-54e5-41d9-bd03-081b3b2fe3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_action_search']/input</value>
      <webElementGuid>737e534e-1861-446e-90b4-460f841f930d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2fada3a9-c549-4db9-b42b-f0c8d48bbd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_action_search_input' and @type = 'text' and @placeholder = 'Enter search term']</value>
      <webElementGuid>f34dfc22-287b-4e6f-a9f3-9b8525035a34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
