<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Delete</name>
   <tag></tag>
   <elementGuidId>6b506c9d-b488-4952-bc69-09242d84383e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//lang[@name='action_delete'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pica-table-selection-multi.files-ui-delete > lang[name=&quot;action_delete&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>e49e23e5-498e-406e-a4ad-215debe14949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action_delete</value>
      <webElementGuid>0c980f1d-cb8e-4dcf-bb9f-54b24b9efac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>d6a11f4a-8572-49db-b62e-aa1f1ad0d7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;files_select_header&quot;)/tr[1]/th[@class=&quot;text-right&quot;]/div[@class=&quot;pica-table-selection-context pica-inline hidden-xs text-right&quot;]/a[@class=&quot;pica-table-selection-multi files-ui-delete&quot;]/lang[1]</value>
      <webElementGuid>66a02b65-ee18-4d74-9347-451423520671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//lang[@name='action_delete'])[2]</value>
      <webElementGuid>f0af66c3-fe84-4def-8ffd-f1da4d7ad210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//thead[@id='files_select_header']/tr/th[3]/div[2]/a[6]/lang</value>
      <webElementGuid>60be854a-072b-4dc0-93f4-739df4a40dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restore'])[2]/following::lang[1]</value>
      <webElementGuid>623a896d-7800-4ad2-af57-2e2eb112d976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cut'])[2]/following::lang[2]</value>
      <webElementGuid>1af11f8c-8fb0-4b21-bc47-4435cdc1386a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[2]/preceding::lang[1]</value>
      <webElementGuid>8aab963b-7297-4ff4-b4ed-63839c7f1da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage'])[2]/preceding::lang[2]</value>
      <webElementGuid>949f4842-6813-4a94-bcce-db75cf684dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/lang</value>
      <webElementGuid>27a267f2-61cc-485c-9125-dde6a377d28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'action_delete' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>57ba6fa7-5c1e-4918-a57b-d915f1d407ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
