<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>log_icon</name>
   <tag></tag>
   <elementGuidId>153c1aa7-2adc-4469-aa5a-1ff41ef086f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_logo_small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d875a5f-1174-45fc-bc6b-8d73095ef622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_logo_small</value>
      <webElementGuid>5dc4d959-e0dc-463b-855d-31b8a8c96213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_logo_small&quot;)</value>
      <webElementGuid>0db1be0b-629f-4267-a31c-a99fd759c584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pica_logo_small']</value>
      <webElementGuid>7b3406e5-4ef0-4201-8a25-319045e8727c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_logo']/div</value>
      <webElementGuid>0a9637e3-0e1a-4e82-b9a6-72da4c3ced86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>90cb0768-f087-4b9a-9934-7b0d39e9af6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pica_logo_small']</value>
      <webElementGuid>1010bf83-74f0-4235-8a95-9b53dc58c704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
