<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input form-organization</name>
   <tag></tag>
   <elementGuidId>776f2c40-82ff-4fcf-8b06-4e58f9de1ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_account_organizations > div.pica-inputlist-taginput.pica-taginput.form-group.input-group > div.pica-taginput-div.form-control > input.pica-taginput-input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9086dd2-0224-46e4-b983-5e456a78b15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6d8a8bd-ef1c-4fac-a955-9629890296a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-taginput-input form-control</value>
      <webElementGuid>45cfa635-013c-41ee-8dce-54fc91a80b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_add_organization_by_name</value>
      <webElementGuid>ec1f2310-63bc-43db-b2c4-0c1db5547943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add an organization by name</value>
      <webElementGuid>f3127081-f0fc-4de2-9651-ad932beb50f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_organizations&quot;)/div[@class=&quot;pica-inputlist-taginput pica-taginput form-group input-group&quot;]/div[@class=&quot;pica-taginput-div form-control&quot;]/input[@class=&quot;pica-taginput-input form-control&quot;]</value>
      <webElementGuid>805ddfe0-2447-4948-afb7-bca977a367de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[10]</value>
      <webElementGuid>425355b9-8499-43d5-973f-3adab1febcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_organizations']/div/div/input</value>
      <webElementGuid>77b59a9d-c74a-4a2f-b1c8-2f5845cecfd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>0578bbe8-928e-44f4-b6a9-a7ad1f190b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Add an organization by name']</value>
      <webElementGuid>82b590ae-eeb7-4f60-ba98-5d64fa43bee1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
