<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>researh_bar</name>
   <tag></tag>
   <elementGuidId>662e5c37-e429-4581-baad-abb46265241a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_action_search_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ad18ce7-fde4-4c7a-ab5f-f4fce67446de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_action_search_input</value>
      <webElementGuid>43dbb59d-f1b9-4008-9b41-c971cf77e2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57ec13e8-6f60-47bc-a1e8-805a9f2b0fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_search</value>
      <webElementGuid>ba3237f8-a09d-4863-b2c2-c7794428e9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>search input</value>
      <webElementGuid>e4edff67-d198-4454-920b-87e5465c2965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter search term</value>
      <webElementGuid>78ce6e3e-1e97-4595-828a-31b4dad8482c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_action_search_input&quot;)</value>
      <webElementGuid>7f8a45e9-6fa4-4813-87d9-dace872ec643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_action_search_input']</value>
      <webElementGuid>febaf2d0-6656-458e-895c-1f1ccb2de48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_action_search']/input</value>
      <webElementGuid>11ec9f0e-ee67-44ed-b041-29d66ae5fde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dd63caf6-a794-4ce8-8346-efa8b67cf8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_action_search_input' and @type = 'text' and @placeholder = 'Enter search term']</value>
      <webElementGuid>6e90819f-3bd8-45f4-97cc-24f0c84b2777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
