<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Organizations</name>
   <tag></tag>
   <elementGuidId>720651b2-7d47-419a-922b-dc80056a54ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.hidden-xs.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94752230-f755-47d0-8269-7939511b3685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Organizations
                        </value>
      <webElementGuid>37691b44-bde0-4d15-be56-0ecbf87eeabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_dialog&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/ul[@class=&quot;pica-space pica-nav-tabs nav nav-tabs&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>355f0476-2c02-455d-8db4-c5cb51b4c863</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_dialog']/div/div/div[2]/ul/li[6]/a</value>
      <webElementGuid>d5d9f83f-8f48-4b8a-bb3e-bc1cb60a372c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[3]/following::a[1]</value>
      <webElementGuid>6c8e7769-cbe9-49a2-ab0c-a02995a14ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folders'])[3]/following::a[2]</value>
      <webElementGuid>e15bf1fe-824e-44bf-a792-457fc7c3e4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/preceding::a[1]</value>
      <webElementGuid>999a4208-7834-4264-b927-bd67aa4a6043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>c9389ed8-92df-4ad0-b9c7-a5a42c8d1d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
                            Organizations
                        ' or . = '
                            Organizations
                        ')]</value>
      <webElementGuid>39b394e2-a908-4923-9929-3ad33fc7d4a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
