<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Notes_pica_account_password_1</name>
   <tag></tag>
   <elementGuidId>e9189b0c-8b9c-4020-b4b3-057f5489dc1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_account_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pica_account_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7644f4e-df13-4f23-97ba-3b37f6174d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_account_password</value>
      <webElementGuid>6244a488-b9ba-4f76-893d-290a38604615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-password form-control</value>
      <webElementGuid>388221a3-3e12-4ab6-8049-d090e5b3e087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2b57c57-4b8f-4424-aca2-dba267e87d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>541020b0-1c7d-4f89-80f5-42435ed74208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_password</value>
      <webElementGuid>5694d23e-15a4-45c3-9bc8-c9f919d34a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ab8d42a8-b237-4763-8dc0-78a8142b5b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Password policy</value>
      <webElementGuid>bcd1833e-bce0-4a58-b089-44fc19eeda5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>popover</value>
      <webElementGuid>7a33b4e2-c14e-4c9f-8ec5-966d96aac47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>67885a50-faa8-42e3-8120-8b38c6d23db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>517715f2-6b06-4996-8e50-d196bf10eedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trigger</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>e663b613-415c-4818-a4cf-f15bc17dcadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0035cc6-c9ed-494a-9821-4f60be1cb61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-content</name>
      <type>Main</type>
      <value>&lt;h5>&lt;lang name=&quot;password_policy_uppercase&quot; class=&quot;profile_password_policy_uppercase pica-space-right-small label label-danger&quot;>At least one upper case letter&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_lowercase&quot; class=&quot;profile_password_policy_lowercase pica-space-right-small label label-danger&quot;>At least one lower case letter&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_digit&quot; class=&quot;profile_password_policy_digit pica-space-right-small label label-danger&quot;>At least one number&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_special&quot; class=&quot;profile_password_policy_special pica-space-right-small label label-danger&quot;>At least one special character&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_count&quot; class=&quot;profile_password_policy_count pica-space-right-small label label-danger&quot;>At least 8 characters&lt;/lang>&lt;/h5></value>
      <webElementGuid>9aafeb47-71b9-4633-b141-8c2e7ce94568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Password policy</value>
      <webElementGuid>c29a6742-b0c0-4db9-8578-a4bc6a1ffc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>popover756622</value>
      <webElementGuid>819ac37c-1d55-4b3b-97f2-cb16fc47a0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_password&quot;)</value>
      <webElementGuid>2b9745ee-e933-4fa1-890b-72128b151118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_account_password']</value>
      <webElementGuid>589a446e-ef7a-4d7f-9b3a-7c4d735e2482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_dialog']/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>ae00c4b7-00f4-4fc5-8679-aaa526c96086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>aa3e200a-6355-4a00-8188-6d139336133a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_account_password' and @type = 'text' and @placeholder = 'Password' and @title = 'Password policy']</value>
      <webElementGuid>038193af-e88a-4a82-9668-7354e2978017</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
