<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Create Account</name>
   <tag></tag>
   <elementGuidId>175bd8a1-d8b0-4b86-8644-0cdc5fa04e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;string_create&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='string_create']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>35760b23-e27d-47a9-a601-130f93aa1e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>string_create</value>
      <webElementGuid>e28ab613-df47-48f4-8b91-245bfbdbb2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Account</value>
      <webElementGuid>941f0bbb-ac84-4875-93b7-f87dfe68efb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_account&quot;)/lang[1]</value>
      <webElementGuid>0d86fb1b-6191-4174-a071-9ad2ece6d6db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='string_create']</value>
      <webElementGuid>f257ada6-1b9d-4d07-9a81-21664ecc9bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='create_account']/lang</value>
      <webElementGuid>a2f3c3b7-118b-44f2-bc82-313558013a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::lang[1]</value>
      <webElementGuid>7f462cb1-58ad-42b7-91c3-7141f6be3f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::lang[2]</value>
      <webElementGuid>48a36eaf-e25c-4121-bd86-62baac76ed29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Accounts'])[1]/preceding::lang[1]</value>
      <webElementGuid>2eebb1c8-ccd1-45f5-8100-3d01bd22be0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Accounts'])[1]/preceding::lang[2]</value>
      <webElementGuid>96a18267-c760-4d09-9eb7-213c9147387c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Account']/parent::*</value>
      <webElementGuid>db941fbb-587c-43ed-814e-f138e1f13eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/div/ul/li/a/lang</value>
      <webElementGuid>cbfda26b-1988-4865-8472-e55a0d8efed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'string_create' and (text() = 'Create Account' or . = 'Create Account')]</value>
      <webElementGuid>c83e9c01-4a1e-4644-95ea-51dbdf8f6dbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
