<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>password_case</name>
   <tag></tag>
   <elementGuidId>7a701b74-9643-45d7-8136-05df2128212d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_account_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>902b6673-b994-42fa-8136-319220a833bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_account_password</value>
      <webElementGuid>30eb56c0-c0f0-4ba7-91ad-1d72189e3014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-password form-control</value>
      <webElementGuid>d273abba-cc26-480a-b574-b2384c9a2d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>817d5afe-33aa-4a1a-aac7-02f6e8f96018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9c3908e1-4ab6-42ac-823d-5d7dd341b552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_password</value>
      <webElementGuid>ad7097c3-1387-4907-91a6-402456e135aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>e6e6776a-15d3-4ee6-a5b4-a9ad3d87a3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Password policy</value>
      <webElementGuid>eb6d1e11-8e6b-4673-8182-fe847b49e2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>popover</value>
      <webElementGuid>d4f62901-f725-4e12-8b15-e8b85478c74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>341014fb-fa1f-4587-8f4a-230e298076c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>f961d3c1-677b-4d62-a152-0990fd43a7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trigger</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>1c290e4c-735f-48a7-98c0-ea8598572508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d81f21a-1aba-41aa-a69c-0a0fb421698e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-content</name>
      <type>Main</type>
      <value>&lt;h5>&lt;lang name=&quot;password_policy_uppercase&quot; class=&quot;profile_password_policy_uppercase pica-space-right-small label label-danger&quot;>At least one upper case letter&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_lowercase&quot; class=&quot;profile_password_policy_lowercase pica-space-right-small label label-danger&quot;>At least one lower case letter&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_digit&quot; class=&quot;profile_password_policy_digit pica-space-right-small label label-danger&quot;>At least one number&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_special&quot; class=&quot;profile_password_policy_special pica-space-right-small label label-danger&quot;>At least one special character&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_count&quot; class=&quot;profile_password_policy_count pica-space-right-small label label-danger&quot;>At least 8 characters&lt;/lang>&lt;/h5></value>
      <webElementGuid>2a6acdf9-bd46-44d1-a927-ce8679ad8c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Password policy</value>
      <webElementGuid>f85d0cc8-b844-494e-8627-e5b93d71385f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>popover998933</value>
      <webElementGuid>5ceb5a3f-5178-43e8-806a-4dcc47265d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_password&quot;)</value>
      <webElementGuid>e1e0e4b9-8ec9-4259-9cec-ceba225d1e24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_account_password']</value>
      <webElementGuid>c007ffe8-a81e-4f34-8b97-1bd204485748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_dialog']/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>199b06cd-4349-4508-b171-e50218037520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b0995ef8-b85f-4251-a1ab-b05a9c29b501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_account_password' and @type = 'text' and @placeholder = 'Password' and @title = 'Password policy']</value>
      <webElementGuid>85f7d811-701f-4ba5-a55a-341b6db1a7ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
