<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Account created</name>
   <tag></tag>
   <elementGuidId>01c2d0f2-c13e-4ff9-8efb-29b43ed2fdaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/button/lang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b90bbf6a-3f6b-46f5-b11f-c6d38bd9548e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account created</value>
      <webElementGuid>75dee065-ac26-47e6-9bfa-a4c2f1d4f8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification_683139029&quot;)/div[@class=&quot;pica-notification-box alert alert-info&quot;]/span[2]</value>
      <webElementGuid>49f5b184-d647-46c2-b2ff-055adbaee1b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notification_683139029']/div/span[2]</value>
      <webElementGuid>35be6455-1ae8-4dd3-a782-2cbe2468b540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'pica_footer', '&quot;', ')/div[@class=', '&quot;', 'pica-pipe-group', '&quot;', ']')])[1]/following::span[2]</value>
      <webElementGuid>93f299df-3c27-48cd-b9aa-f4d8f045fb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::span[2]</value>
      <webElementGuid>043881b4-72a7-4bcf-bd9e-c035e59f43bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[7]/preceding::span[1]</value>
      <webElementGuid>b8787df9-45c3-468f-a8a9-077b97f70bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span[2]</value>
      <webElementGuid>3e1bce8a-a980-4c44-9cf0-99a7a6c02182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Account created' or . = 'Account created')]</value>
      <webElementGuid>3deffd79-c440-45ce-97de-d39392538e0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
